name: "Energy Smart Bridge"
description: "Energy Smart Bridge"
version: "0.0.6"
slug: "energy_smart_bridge"
image: "ghcr.io/starsoccer/energysmartbridge/{arch}"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  443/tcp: 443
  8001/tcp: null
ports_description:
  443/tcp: "The HTTPS port to which the EnergySmart dongle will connect. Must be 443."
  8001/tcp: "The HTTP port of the bridge server. Use if you'll be running your own reverse proxy and terminating SSL elsewhere."
options:
  MQTT_PORT: 1883
  MQTT_SERVER: null
  MQTT_USERNAME: null
  MQTT_PASSWORD: null
  MQTT_PREFIX: "energysmart"
  MQTT_DISCOVERY_PREFIX: "homeassistant"
  DEBUG: false
schema:
  MQTT_PORT: port
  MQTT_SERVER: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  MQTT_PREFIX: str
  MQTT_DISCOVERY_PREFIX: str
  DEBUG: bool
